---
apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: "s3-data-pvc"
  labels:
    app.kubernetes.io/name: "impact-kids-app"
    app.kubernetes.io/component: "s3"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.parameters.s3.storage }}"
