// <auto-generated />
using System;
using GSBC.ImpactKids.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GSBC.ImpactKids.Grpc.Data.Migrations
{
    [DbContext(typeof(GsbcDbContext))]
    [Migration("20251014012705_1760405222")]
    partial class _1760405222
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleBook", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BibleBooks");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleChapter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BibleChapters");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleVerse", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Verse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BookId", "ChapterId", "Id");

                    b.HasIndex("ChapterId");

                    b.ToTable("BibleVerses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolTermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTermId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleVerse", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleBook", "Book")
                        .WithMany("Verses")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleChapter", "Chapter")
                        .WithMany("Verses")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbService", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", "SchoolTerm")
                        .WithMany("Services")
                        .HasForeignKey("SchoolTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTerm");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleBook", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Bible.DbBibleChapter", b =>
                {
                    b.Navigation("Verses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", b =>
                {
                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
