// <auto-generated />
using System;
using GSBC.ImpactKids.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GSBC.ImpactKids.Grpc.Data.Migrations
{
    [DbContext(typeof(GsbcDbContext))]
    [Migration("20251105022133_1762309289")]
    partial class _1762309289
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbBibleVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Verse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BibleVerses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbDollarStoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DollarDoosMade")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("DollarStoreEntries");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolTermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTermId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemorisationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("FiveDollaryDoosGiven")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemoryVerseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OneDollaryDooGiven")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("VerseRecited")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MemoryVerseId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("PersonId", "ServiceId", "MemoryVerseId")
                        .IsUnique();

                    b.ToTable("MemorisationEntries");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemoryVerseListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemoryVerseListId");

                    b.ToTable("MemoryVerses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseBibleVerseRelationship", b =>
                {
                    b.Property<Guid>("MemoryVersesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibleVersesId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryVersesId", "BibleVersesId");

                    b.HasIndex("BibleVersesId");

                    b.ToTable("DbMemoryVerseBibleVerseRelationship");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolTermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTermId");

                    b.ToTable("MemoryVerseLists");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseServiceRelationship", b =>
                {
                    b.Property<Guid>("MemoryVersesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryVersesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("DbMemoryVerseServiceRelationship");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ElvantoId")
                        .HasColumnType("text");

                    b.Property<bool>("FamilyGuardian")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolGradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElvantoId")
                        .IsUnique();

                    b.HasIndex("SchoolGradeId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbSchoolGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ElvantoId")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NextGradeId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousGrade")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SchoolGrades");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbDollarStoreEntry", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbService", "Service")
                        .WithOne("DollarStoreEntry")
                        .HasForeignKey("GSBC.ImpactKids.Grpc.Data.Models.DbDollarStoreEntry", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbService", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", "SchoolTerm")
                        .WithMany("Services")
                        .HasForeignKey("SchoolTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchoolTerm");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemorisationEntry", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", "MemoryVerse")
                        .WithMany("MemorisationEntries")
                        .HasForeignKey("MemoryVerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryVerse");

                    b.Navigation("Person");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", "MemoryVerseList")
                        .WithMany("MemoryVerses")
                        .HasForeignKey("MemoryVerseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryVerseList");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseBibleVerseRelationship", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbBibleVerse", null)
                        .WithMany()
                        .HasForeignKey("BibleVersesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", null)
                        .WithMany()
                        .HasForeignKey("MemoryVersesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", "SchoolTerm")
                        .WithMany()
                        .HasForeignKey("SchoolTermId");

                    b.Navigation("SchoolTerm");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseServiceRelationship", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", null)
                        .WithMany()
                        .HasForeignKey("MemoryVersesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbSchoolGrade", "SchoolGrade")
                        .WithMany()
                        .HasForeignKey("SchoolGradeId");

                    b.Navigation("SchoolGrade");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbSchoolTerm", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbService", b =>
                {
                    b.Navigation("DollarStoreEntry");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", b =>
                {
                    b.Navigation("MemorisationEntries");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", b =>
                {
                    b.Navigation("MemoryVerses");
                });
#pragma warning restore 612, 618
        }
    }
}
