// <auto-generated />
using System;
using GSBC.ImpactKids.Grpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GSBC.ImpactKids.Grpc.Data.Migrations
{
    [DbContext(typeof(GsbcDbContext))]
    partial class GsbcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttendanceItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttendanceRecordId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ItemReturned")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<bool>("RewardGiven")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceItemTypeId");

                    b.HasIndex("AttendanceRecordId");

                    b.ToTable("AttendanceItemRecords");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresReturning")
                        .HasColumnType("boolean");

                    b.Property<int?>("Reward")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("AttendanceItemTypes");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PickupRequested")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PickupRequestedUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SignedIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SignedInUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("SignedOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SignedOutUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PickupRequestedUserId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SignedInUserId");

                    b.HasIndex("SignedOutUserId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbPickupDisplayKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RotatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RotatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenSigningKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RotatedByUserId");

                    b.ToTable("PickupDisplayKeys");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbBibleVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BookNumber")
                        .HasColumnType("integer");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Verse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VerseNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("BibleVerses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbDollarStoreEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("DollarDoosMade")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("DollarStoreEntries");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("GoogleSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSub")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Games.DbGameBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BehaviourPointsMultiplier")
                        .HasColumnType("integer");

                    b.Property<int>("BonusPoints")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentGame")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayMode")
                        .HasColumnType("integer");

                    b.Property<bool>("Hidden")
                        .HasColumnType("boolean");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsMultiplier")
                        .HasColumnType("integer");

                    b.Property<int?>("RevealStep")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("StepPoints")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("GameBoards");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Games.DbGamePointRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Awarded")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AwardedUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("GameNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Place")
                        .HasColumnType("integer");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<int>("TeamIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AwardedUserId");

                    b.HasIndex("ServiceId");

                    b.ToTable("GamePointRecords");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemorisationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("FiveDollaryDoosGiven")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MemoryVerseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("OneDollaryDooGiven")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<bool>("VerseRecited")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MemoryVerseId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("PersonId", "ServiceId", "MemoryVerseId")
                        .IsUnique();

                    b.ToTable("MemorisationEntries");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemoryVerseListId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReferenceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemoryVerseListId");

                    b.ToTable("MemoryVerses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseBibleVerseRelationship", b =>
                {
                    b.Property<Guid>("MemoryVersesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BibleVersesId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryVersesId", "BibleVersesId");

                    b.HasIndex("BibleVersesId");

                    b.ToTable("DbMemoryVerseBibleVerseRelationship");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolTermId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTermId");

                    b.ToTable("MemoryVerseLists");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseServiceRelationship", b =>
                {
                    b.Property<Guid>("MemoryVersesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uuid");

                    b.HasKey("MemoryVersesId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("DbMemoryVerseServiceRelationship");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbVirtualMemorisationEntry", b =>
                {
                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MemoryVerseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("FiveDollaryDoosGiven")
                        .HasColumnType("boolean");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("OneDollaryDooGiven")
                        .HasColumnType("boolean");

                    b.Property<bool>("VerseHasBeenRecitedBefore")
                        .HasColumnType("boolean");

                    b.Property<bool>("VerseRecited")
                        .HasColumnType("boolean");

                    b.HasKey("PersonId", "ServiceId", "MemoryVerseId");

                    b.HasIndex("MemoryVerseId");

                    b.HasIndex("ServiceId");

                    b.ToTable((string)null);

                    b.ToView("VirtualMemorisationEntries", (string)null);
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbAllergen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Allergens");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbAllergy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AllergenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Severe")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AllergenId");

                    b.HasIndex("PersonId");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbMedicalNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MedicalTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Severe")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MedicalTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("MedicalNotes");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbMedicalType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalTypes");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElvantoId")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("FamilyGuardian")
                        .HasColumnType("boolean");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("FirstTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaConsent")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("NotRequested");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolGradeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ElvantoId")
                        .IsUnique();

                    b.HasIndex("SchoolGradeId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbSchoolGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ElvantoId")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("NextGradeId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousGrade")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("SchoolGrades");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("SchoolTermId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolTermId");

                    b.HasIndex("ServiceTypeId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.School.DbSchoolTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbElvantoFamilyLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ElvantoFamilyId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LinkedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LocalFamilyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ElvantoFamilyId")
                        .IsUnique();

                    b.HasIndex("LocalFamilyId")
                        .IsUnique();

                    b.ToTable("ElvantoFamilyLinks");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbElvantoFieldSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppHash")
                        .HasColumnType("text");

                    b.Property<string>("AppValue")
                        .HasColumnType("text");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSeenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastSeenValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "FieldName")
                        .IsUnique();

                    b.ToTable("ElvantoFieldSnapshots");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbFieldChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ValueHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "FieldName", "ChangedAt");

                    b.ToTable("FieldChangeLogs");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<string>("FromValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SyncOperationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "OccurredAt");

                    b.HasIndex("SyncOperationId", "OccurredAt");

                    b.ToTable("SyncAuditLogs");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncOperation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PlanExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.ToTable("SyncOperations");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncPendingReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElvantoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MatchConfidence")
                        .HasColumnType("integer");

                    b.Property<string>("MatchStrategy")
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PersonName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SyncOperationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SyncOperationId");

                    b.HasIndex("PersonId", "ElvantoId")
                        .IsUnique();

                    b.ToTable("PendingReviews");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncPlannedChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AppliedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ElvantoId")
                        .HasColumnType("text");

                    b.Property<string>("FieldName")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ObservedAppHash")
                        .HasColumnType("text");

                    b.Property<string>("ObservedAppValue")
                        .HasColumnType("text");

                    b.Property<string>("ObservedElvantoHash")
                        .HasColumnType("text");

                    b.Property<string>("ObservedElvantoValue")
                        .HasColumnType("text");

                    b.Property<Guid?>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProposedValue")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusReason")
                        .HasColumnType("text");

                    b.Property<Guid>("SyncOperationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "DecidedAt");

                    b.HasIndex("SyncOperationId", "Status");

                    b.ToTable("PlannedChanges");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceItemRecord", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceItemType", "AttendanceItemType")
                        .WithMany()
                        .HasForeignKey("AttendanceItemTypeId");

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceRecord", "AttendanceRecord")
                        .WithMany()
                        .HasForeignKey("AttendanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceItemType");

                    b.Navigation("AttendanceRecord");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbAttendanceRecord", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbUser", "PickupRequestedUser")
                        .WithMany()
                        .HasForeignKey("PickupRequestedUserId");

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbUser", "SignedInUser")
                        .WithMany()
                        .HasForeignKey("SignedInUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbUser", "SignedOutUser")
                        .WithMany()
                        .HasForeignKey("SignedOutUserId");

                    b.Navigation("Person");

                    b.Navigation("PickupRequestedUser");

                    b.Navigation("Service");

                    b.Navigation("SignedInUser");

                    b.Navigation("SignedOutUser");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Attendance.DbPickupDisplayKey", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbUser", "RotatedByUser")
                        .WithMany()
                        .HasForeignKey("RotatedByUserId");

                    b.Navigation("RotatedByUser");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.DbDollarStoreEntry", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", "Service")
                        .WithOne("DollarStoreEntry")
                        .HasForeignKey("GSBC.ImpactKids.Grpc.Data.Models.DbDollarStoreEntry", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Games.DbGameBoard", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GSBC.ImpactKids.Grpc.Data.Models.Games.DbGame", "Games", b1 =>
                        {
                            b1.Property<Guid>("DbGameBoardId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.PrimitiveCollection<string>("Alliances")
                                .IsRequired();

                            b1.Property<bool>("Hidden");

                            b1.Property<int?>("Multiplier");

                            b1.Property<string>("Name");

                            b1.Property<int>("Number");

                            b1.PrimitiveCollection<string>("PlacementPoints");

                            b1.Property<bool>("Planned");

                            b1.HasKey("DbGameBoardId", "__synthesizedOrdinal");

                            b1.ToTable("GameBoards");

                            b1.ToJson("Games");

                            b1.WithOwner()
                                .HasForeignKey("DbGameBoardId");
                        });

                    b.OwnsMany("GSBC.ImpactKids.Grpc.Data.Models.Games.DbGameTeam", "Teams", b1 =>
                        {
                            b1.Property<Guid>("DbGameBoardId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Colour")
                                .IsRequired();

                            b1.Property<int>("Index");

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.HasKey("DbGameBoardId", "__synthesizedOrdinal");

                            b1.ToTable("GameBoards");

                            b1.ToJson("Teams");

                            b1.WithOwner()
                                .HasForeignKey("DbGameBoardId");
                        });

                    b.Navigation("Games");

                    b.Navigation("Service");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Games.DbGamePointRecord", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbUser", "AwardedUser")
                        .WithMany()
                        .HasForeignKey("AwardedUserId");

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardedUser");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemorisationEntry", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", "MemoryVerse")
                        .WithMany("MemorisationEntries")
                        .HasForeignKey("MemoryVerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryVerse");

                    b.Navigation("Person");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", "MemoryVerseList")
                        .WithMany("MemoryVerses")
                        .HasForeignKey("MemoryVerseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryVerseList");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseBibleVerseRelationship", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.DbBibleVerse", null)
                        .WithMany()
                        .HasForeignKey("BibleVersesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", null)
                        .WithMany()
                        .HasForeignKey("MemoryVersesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.School.DbSchoolTerm", "SchoolTerm")
                        .WithMany()
                        .HasForeignKey("SchoolTermId");

                    b.Navigation("SchoolTerm");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseServiceRelationship", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", null)
                        .WithMany()
                        .HasForeignKey("MemoryVersesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbVirtualMemorisationEntry", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", "MemoryVerse")
                        .WithMany()
                        .HasForeignKey("MemoryVerseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MemoryVerse");

                    b.Navigation("Person");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbAllergy", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbAllergen", "Allergen")
                        .WithMany()
                        .HasForeignKey("AllergenId");

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany("Allergies")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbMedicalNote", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbMedicalType", "MedicalType")
                        .WithMany()
                        .HasForeignKey("MedicalTypeId");

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany("MedicalNotes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedicalType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbSchoolGrade", "SchoolGrade")
                        .WithMany()
                        .HasForeignKey("SchoolGradeId");

                    b.Navigation("SchoolGrade");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.School.DbSchoolTerm", "SchoolTerm")
                        .WithMany("Services")
                        .HasForeignKey("SchoolTermId");

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbServiceType", "ServiceType")
                        .WithMany()
                        .HasForeignKey("ServiceTypeId");

                    b.Navigation("SchoolTerm");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncAuditLog", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncOperation", "SyncOperation")
                        .WithMany("AuditLogs")
                        .HasForeignKey("SyncOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncOperation");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncPendingReview", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncOperation", "SyncOperation")
                        .WithMany()
                        .HasForeignKey("SyncOperationId");

                    b.Navigation("Person");

                    b.Navigation("SyncOperation");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncPlannedChange", b =>
                {
                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncOperation", "SyncOperation")
                        .WithMany("PlannedChanges")
                        .HasForeignKey("SyncOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("SyncOperation");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerse", b =>
                {
                    b.Navigation("MemorisationEntries");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.MemoryVerses.DbMemoryVerseList", b =>
                {
                    b.Navigation("MemoryVerses");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.People.DbPerson", b =>
                {
                    b.Navigation("Allergies");

                    b.Navigation("MedicalNotes");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.DbService", b =>
                {
                    b.Navigation("DollarStoreEntry");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Scheduling.School.DbSchoolTerm", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("GSBC.ImpactKids.Grpc.Data.Models.Sync.DbSyncOperation", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("PlannedChanges");
                });
#pragma warning restore 612, 618
        }
    }
}
