---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "sql-service"
  labels:
    app.kubernetes.io/name: "impact-kids-app"
    app.kubernetes.io/component: "sql"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "impact-kids-app"
    app.kubernetes.io/component: "sql"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "tcp"
      protocol: "TCP"
      port: 1433
      targetPort: 1433
