---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "rabbitmq-secrets"
  labels:
    app.kubernetes.io/name: "impact-kids-app"
    app.kubernetes.io/component: "rabbitmq"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  RABBITMQ_DEFAULT_PASS: {{ rabbitmqPass | b64enc }}
type: "Opaque"
