using System.Text.Json.Serialization;

namespace GSBC.ImpactKids.Shared.Contracts.Entities.Features.Games;

/// <summary>
/// A single append-only points delta for a team during a service.
/// Totals are the sum of the deltas rather than a mutable counter, so records
/// created offline on multiple devices merge without overwriting each other.
/// <see cref="Id"/> is generated by the client so re-sending a queued record is idempotent.
/// </summary>
[ProtoContract(ImplicitFields = ImplicitFields.AllPublic)]
public record GamePointRecord : IIdentifiable
{
    public required Guid Id { get; init; }

    /// <summary>Positional, matching <see cref="GameTeamDefinition.Index"/> on the board.</summary>
    public required int TeamIndex { get; init; }

    public required int Points { get; init; }

    /// <summary>
    /// Which game of the night this belongs to, or <c>null</c> for behaviour points,
    /// which are awarded outside of any game but still count toward the total.
    /// </summary>
    public required int? GameNumber { get; init; }

    /// <summary>
    /// Set when the tap scored an alliance: one record per member team, all sharing this
    /// id. It is what lets undo take the whole award back rather than half of it.
    /// <para>
    /// A placement round shares one too - every side placed in the same race, whatever
    /// each of them scored - which is what makes a round a thing that can be undone,
    /// edited or read back as a finishing order.
    /// </para>
    /// </summary>
    public Guid? GroupId { get; init; }

    /// <summary>
    /// Where this team finished, 1 based, for a game scored by placement. Null for
    /// ordinary tapped points.
    /// <para>
    /// Stored rather than worked out from <see cref="Points"/>, because a placing and
    /// what it is worth are not the same fact: when only the top three score, fourth
    /// place is a real placing worth nothing, and inferring it from a zero would make it
    /// indistinguishable from a team that never ran.
    /// </para>
    /// <para>
    /// Competition ranking, matching the board and the reveal - two teams tied for first
    /// are both 1, and the next one is 3.
    /// </para>
    /// </summary>
    public int? Place { get; init; }

    [ProtoIgnore]
    [JsonIgnore]
    public bool IsBehaviour => GameNumber == null;

    public required DateTime Awarded { get; init; }

    // Also ignored for JSON - these records are cached in browser storage for offline use.
    [ProtoIgnore]
    [JsonIgnore]
    public DateTime LocalAwarded => Awarded.ToLocalTime();

    public bool Deleted { get; init; }

    public required Guid  ServiceId     { get; init; }
    public          Guid? AwardedUserId { get; init; }
}
