using System.Text.Json.Serialization;

namespace GSBC.ImpactKids.Shared.Contracts.Entities.Features.Games;

/// <summary>
/// A single append-only points delta for a team during a service.
/// Totals are the sum of the deltas rather than a mutable counter, so records
/// created offline on multiple devices merge without overwriting each other.
/// <see cref="Id"/> is generated by the client so re-sending a queued record is idempotent.
/// </summary>
[ProtoContract(ImplicitFields = ImplicitFields.AllPublic)]
public record GamePointRecord : IIdentifiable
{
    public required Guid Id { get; init; }

    public required GameTeam Team   { get; init; }
    public required int      Points { get; init; }

    /// <summary>
    /// Which game of the night this belongs to, or <c>null</c> for behaviour points,
    /// which are awarded outside of any game but still count toward the total.
    /// </summary>
    public required int? GameNumber { get; init; }

    [ProtoIgnore]
    [JsonIgnore]
    public bool IsBehaviour => GameNumber == null;

    public required DateTime Awarded { get; init; }

    // Also ignored for JSON - these records are cached in browser storage for offline use.
    [ProtoIgnore]
    [JsonIgnore]
    public DateTime LocalAwarded => Awarded.ToLocalTime();

    public bool Deleted { get; init; }

    public required Guid  ServiceId     { get; init; }
    public          Guid? AwardedUserId { get; init; }
}
