name: Release Charts

on:
  workflow_call:
    inputs:
      version:
        description: 'The version to update to'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: asherslab/gsbc.argo
          path: argo
          token: ${{ secrets.ARGO_REPO_TOKEN }}

      - name: Update Helm Chart Version
        working-directory: app-definitions
        run: |
          # The current version is stored in inputs.version, we need to rewrite the charts.yaml file with the new version
          # However we can only replace the version: property if it is at the start of a line
          echo "Updating impact-kids.yaml version to ${{ inputs.version }}"
          sed -i "s/targetRevision: \(.*\) #helm/targetRevision: ${{ inputs.version }} #helm/g" impact-kids.yaml

      - name: Commit and push changes (if any)
        shell: bash
        env:
          CI_COMMIT_MESSAGE: update impact-kids.yaml with latest chart version
          CI_COMMIT_AUTHOR: github-actions[bot]
          CI_COMMIT_EMAIL: username@users.noreply.github.com
        run: |
          cd argo
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          if [[ `git status --porcelain --untracked-files=no` ]]; then
            # Changes
            git add app-definitions/impact-kids.yaml
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          else
            # No changes
            echo "no changes to latest posts"
            exit 0
          fi