name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Generate Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.4.0

      - name: Push Release Tag
        run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

      - name: Set Chart Version
        run: |
          echo "version: ${{ steps.version.outputs.version }}" > charts/impact-kids/Chart.yaml
          echo "appVersion: ${{ steps.version.outputs.version }}" > charts/impact-kids/Chart.yaml
          echo "versionTag: ${{ steps.version.outputs.version }}" > charts/impact-kids/templates/_helpers.tpl

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: charts/impact-kids
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  build-migrations:
    runs-on: ubuntu-latest
    needs: version

    steps:
    - uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Migrations
      uses: docker/build-push-action@v6
      with:
        file: GSBC.ImpactKids.Workers.DbMigrations/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: asherslab/gsbc-kids-migrations:latest,asherslab/gsbc-kids-migrations:${{needs.version.outputs.version}}

  build-grpc:
    runs-on: ubuntu-latest
    needs: version

    steps:
    - uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and Push Grpc
      uses: docker/build-push-action@v6
      with:
        file: GSBC.ImpactKids.Grpc/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: asherslab/gsbc-kids-grpc:latest,asherslab/gsbc-kids-grpc:${{needs.version.outputs.version}}

  build-web:
    runs-on: ubuntu-latest
    needs: version

    steps:
    - uses: actions/checkout@v4
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Web
      uses: docker/build-push-action@v6
      with:
        file: GSBC.ImpactKids.Web/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: asherslab/gsbc-kids-web:latest,asherslab/gsbc-kids-web:${{needs.version.outputs.version}}
  
